### ISSUE TITLE
[ERR] skdh.preprocessing.CalibrateAccelerometer: the 'axes' parameter is not supported in the pandas implementation of transpose()

### ISSUE THREAD

**Issue by rmndrs89** [pfizer-opensource/scikit-digital-health#129]
I have a `pandas.DataFrame` that looks like:

```python
                           time   accel_x   accel_y   accel_z    gyro_x    gyro_y    gyro_z  temperature
0 2023-11-17 00:00:02.841461248  0.116943 -1.023438 -0.128418  0.610352  0.610352  0.061035    34.375000
1 2023-11-17 00:00:02.851403008  0.112549 -1.023682 -0.126709  0.793457  0.488281  0.122070    34.367676
2 2023-11-17 00:00:02.861344768  0.113770 -1.025635 -0.131104  0.854492  0.366211  0.061035    34.360352
3 2023-11-17 00:00:02.871286784  0.113770 -1.022705 -0.134277  0.732422  0.488281  0.000000    34.353027
4 2023-11-17 00:00:02.881228800  0.116699 -1.022461 -0.131836  0.610352  0.549316  0.000000    34.345703
```

The dataframe contains accelerometer, gyroscope and temperature data from 7 days continuous monitoring. Now, I would want to calibrate the accelerometer data according to the Van Hees (2014) implementation, hence I did:

```python
from skdh.preprocessing import CalibrateAccelerometer

calibrate = CalibrateAccelerometer()
results = calibrate.predict(time=df["time"], accel=df[[f"accel_{x}" for x in ['x', 'y', 'z']]], fs=100.)
```

However, I get an error saying that **the 'axes' parameter is not supported in the pandas implementation of transpose()**:
> Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "d:\Projects\myngmt\env\lib\site-packages\skdh\base.py", line 30, in magic
    return_vals = method(self, **kwargs)
  File "d:\Projects\myngmt\env\lib\site-packages\skdh\preprocessing\calibrate.py", line 173, in predict
    store.acc_rsd = accel[: nh + i_h * n12h]
  File "d:\Projects\myngmt\env\lib\site-packages\skdh\preprocessing\calibrate.py", line 347, in acc_rsd
    self._acc_rsd, self._acc_rm = moving_sd(
  File "d:\Projects\myngmt\env\lib\site-packages\skdh\utility\math.py", line 231, in moving_sd
    x = moveaxis(a, axis, -1)
  File "d:\Projects\myngmt\env\lib\site-packages\numpy\core\numeric.py", line 1460, in moveaxis
    result = transpose(order)
  File "d:\Projects\myngmt\env\lib\site-packages\pandas\core\frame.py", line 3669, in transpose
    nv.validate_transpose(args, {})
  File "d:\Projects\myngmt\env\lib\site-packages\pandas\compat\numpy\function.py", line 88, in __call__
    validate_args_and_kwargs(
  File "d:\Projects\myngmt\env\lib\site-packages\pandas\util\_validators.py", line 223, in validate_args_and_kwargs
    validate_kwargs(fname, kwargs, compat_args)
  File "d:\Projects\myngmt\env\lib\site-packages\pandas\util\_validators.py", line 165, in validate_kwargs
    _check_for_default_values(fname, kwds, compat_args)
  File "d:\Projects\myngmt\env\lib\site-packages\pandas\util\_validators.py", line 81, in _check_for_default_values
    raise ValueError(
ValueError: the 'axes' parameter is not supported in the pandas implementation of transpose()

However, I do not make a call to `pandas`, neither could I find where this error comes from. (I suspect, however, from the `moveaxis` call when calculating the moving mean and standard deviation). 

Anyone who could help out?

Best regards,
Robbin

**Comment by LukasAdamowicz** [comment]
Hi, that error will come because you are passing in pandas dataframe. You should be able to avoid this by using `.values` when you pass in the parts of the dataframe, ie 

```from skdh.preprocessing import CalibrateAccelerometer

calibrate = CalibrateAccelerometer()
results = calibrate.predict(time=df["time"].values, accel=df[[f"accel_{x}" for x in ['x', 'y', 'z']]].values, fs=100.)
```

Also please note that while it will be fine for `CalibrateAccelerometer`, SKDH normally requires timestamps passed in as seconds from 1970, so you would need to convert your time column. For this case it doesn't matter, but for other use cases it would be required.
